name: Build and Deploy Android App to Google Play

on:
  push:
    branches:
      - development  # Trigger on push to the development branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install Dependencies
      run: |
        npm install
        # Removed `npx pod-install ios` since it's for iOS

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk-manager-action@v2
      with:
        sdk-version: '30.0.3'
        ndk-version: '21.4.7075529'

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-android-ci-cd.keystore

    - name: Build APK for Release
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development' && success()

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Google Play credentials
      uses: r0adkll/upload-google-play-action@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
        packageName: "com.yourapp.package"  # Replace with your app's package name
        releaseFile: android/app/build/outputs/apk/release/app-release.apk
        track: production  # Can be 'alpha', 'beta', 'production'
