name: Build and Deploy Android App to Google Play

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Dependencies
      run: npm ci

    - name: Ensure autolinking.json File Exists
      run: |
        mkdir -p android/build/generated/autolinking
        if [ ! -f android/build/generated/autolinking/autolinking.json ]; then
          echo '{}' > android/build/generated/autolinking/autolinking.json
        fi

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30.0.3'
        ndk-version: '21.4.7075529'

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Clean Gradle Cache
      run: |
        cd android
        ./gradlew clean

    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-android-ci-cd.keystore

    - name: Build Android
      run: ./gradlew assembleRelease
      working-directory: android

    - name: Build APK for Release
      run: |
        cd android
        ./gradlew clean assembleRelease --no-daemon --stacktrace --info

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
