name: Build and Deploy Android App to Google Play

on:
  push:
    branches:
      - development  # Trigger on push to the development branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin' # JDK 17 works better with Gradle 7+

    # Install Dependencies
    - name: Install Dependencies
      run: |
        npm ci # Clean install all dependencies

    # Run React Native autolinking
    - name: Run React Native Autolink
      run: npx react-native autolink

    # Ensure the autolinking.json file exists
    - name: Ensure autolinking.json File Exists
      run: |
        mkdir -p android/build/generated/autolinking
        if [ ! -f android/build/generated/autolinking/autolinking.json ]; then
          echo '{}' > android/build/generated/autolinking/autolinking.json
        fi

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30.0.3'
        ndk-version: '21.4.7075529'

    # Ensure gradlew is executable
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    # Clean the Gradle cache
    - name: Clean Gradle Cache
      run: |
        cd android
        ./gradlew clean

    # Decode Keystore
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-android-ci-cd.keystore

    # Build APK for release
    - name: Build APK for Release
      run: |
        cd android
        ./gradlew clean assembleRelease --no-daemon --stacktrace --info

    # Upload APK artifact
    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v3
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development' && success()

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Upload APK to Google Play
    - name: Set up Google Play credentials
      uses: r0adkll/upload-google-play-action@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
        packageName: "com.yourapp.package"  # Replace with your app's package name
        releaseFile: android/app/build/outputs/apk/release/app-release.apk
        track: production  # Options: 'alpha', 'beta', 'production'
